CREATE DATABASE bnb;

USE bnb;

CREATE TABLE reviews (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(25) NOT NULL,
  avatar VARCHAR(25) NOT NULL,
  numDaysAgo INT NOT NULL,
  content VARCHAR(1500)
)