CREATE DATABASE IF NOT EXISTS bnb;

USE bnb;

CREATE TABLE reviews (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(25) NOT NULL,
  avatar VARCHAR(25) NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
  referenceItem INT NOT NULL,
  content VARCHAR(1500)
);